id: PFAD528BE
initial_creation_type: ocr
source_metadata:
  volumes:
    aeb05f93d32a4e619f6556a21d8006e2:
      base_file: v093.txt
      image_group_id: I1PD95938
      title: དགེ་སློང་གི་དང་པོའི་ལོ་དྲི་བ།
      total_pages: 1484
      volume_number: 93
